apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260623-234620-pnnl2aja0yhd-service
spec:
  selector:
    app: enterprise-system-20260623-234620-pnnl2aja0yhd
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
